# Generated by Django 6.0.3 on 2026-03-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed _ Success'), ('failed', 'Failed _ Canceled')], default='pending', max_length=20),
        ),
    ]
