# Generated by Django 6.0.3 on 2026-03-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_national_id_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('', '----------'), ('admin', 'Admin'), ('owner', 'Owner'), ('tenant', 'Tenant')], default='', max_length=10, null=True),
        ),
    ]
