# Generated by Django 6.0.4 on 2026-04-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('tenant', 'Tenant')], default='tenant', max_length=10),
        ),
    ]
