# Generated by Django 6.0.3 on 2026-03-15 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contractsignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsignature',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature_info', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='contractsignature',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/%Y/%m/'),
        ),
    ]
