# Generated by Django 6.0.3 on 2026-03-15 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
        ('contracts', '0003_alter_contractsignature_contract_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterModelOptions(
            name='contractsignature',
            options={'verbose_name': 'Contract Signature', 'verbose_name_plural': 'Contract Signatures'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking', verbose_name='Booking'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_file',
            field=models.FileField(upload_to='contracts/', verbose_name='Contract File'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Deposit'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rent Amount'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed',
            field=models.BooleanField(default=False, verbose_name='Signed'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='contractsignature',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature_info', to='contracts.contract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='contractsignature',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/%Y/%m/', verbose_name='Signature Image'),
        ),
        migrations.AlterField(
            model_name='contractsignature',
            name='signed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Signed At'),
        ),
    ]
