# Generated by Django 6.0.4 on 2026-04-24 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_property_alter_booking_tenant'),
        ('handover', '0001_initial'),
        ('properties', '0008_alter_property_options_alter_property_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handover',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='handover',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='handover',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='handover',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_handovers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='handover',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='handover',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='handover',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_handovers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='handover',
            index=models.Index(fields=['status'], name='handover_ha_status_05ee4b_idx'),
        ),
        migrations.AddIndex(
            model_name='handover',
            index=models.Index(fields=['property'], name='handover_ha_propert_9ac8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='handover',
            index=models.Index(fields=['booking'], name='handover_ha_booking_5cb48f_idx'),
        ),
    ]
