# Generated by Django 6.0.4 on 2026-04-24 13:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
        ('properties', '0008_alter_property_options_alter_property_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='properties.property'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user'], name='favorites_f_user_id_645357_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['property'], name='favorites_f_propert_1aab54_idx'),
        ),
    ]
