# Generated by Django 6.0.4 on 2026-04-24 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options_message_property_id'),
        ('properties', '0008_alter_property_options_alter_property_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='property_id',
        ),
        migrations.AddField(
            model_name='message',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='properties.property'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='chat_messag_sender__c4389c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver'], name='chat_messag_receive_b6ffa6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['property'], name='chat_messag_propert_b0d7e6_idx'),
        ),
    ]
