# Generated by Django 6.0.3 on 2026-03-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='properties_videos/'),
        ),
    ]
