# Generated by Django 6.0.3 on 2026-03-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_propertyimage_video_propertyvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('studio', 'Studio'), ('supermarket', 'Supermarket'), ('restaurant', 'Restaurant'), ('grocery store', 'Grocery Store')], default='apartment', max_length=50),
        ),
    ]
