# Generated by Django 6.0.3 on 2026-04-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_owner_alter_property_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('studio', 'Studio'), ('supermarket', 'Supermarket'), ('restaurant', 'Restaurant'), ('grocery_store', 'Grocery Store')], default='apartment', max_length=50),
        ),
    ]
